#ifndef CORE_COMPAT_CODEXAPPSERVERCLIENT_WRAPPER_H
#define CORE_COMPAT_CODEXAPPSERVERCLIENT_WRAPPER_H

#include "plugins/backends/codex/CodexAppServerClient.h"

#endif // CORE_COMPAT_CODEXAPPSERVERCLIENT_WRAPPER_H
