isEmpty(QCHAT_TEXT_PROVIDER_PRI_INCLUDED) {
QCHAT_TEXT_PROVIDER_PRI_INCLUDED = 1

TEXT_PROVIDER_DIR = $$PWD

INCLUDEPATH += $$TEXT_PROVIDER_DIR

SOURCES += \
    $$TEXT_PROVIDER_DIR/text_provider.cpp

HEADERS += \
    $$TEXT_PROVIDER_DIR/text_provider.h

}
